#ifndef MVMNT_TYPE_H
#define MVMNT_TYPE_H

/*
 * Copyright (C) 2015
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
  This file defines the interface for the movement type class. This class is
  there to provide defaults for movment costs for untis, so that we don't have
  to provide movement costs for all the terrains in the unit conf files. The
  actual implemeting classes have to be autogenerated since we don't know all
  the different terrains beforehand.
 */

#include "map/tile.hpp" // for tile_t

namespace maw {
namespace common {
namespace unit {

enum class mvmnt_t_e {LAND, SEA, AIR, AMPHIB};

class mvmnt_type {
private:
  mvmnt_t_e type;
public:
  mvmnt_type(mvmnt_t_e type) : type(type) {}
  // the default cost of moving to tile to
  virtual unsigned dflt_mv_cst(tile_t to) const = 0;
  inline mvmnt_t_e get_type() const {return type;}
};
} // end namespace unit
} // end namespace common
} // end namespace maw
#endif // ifndef MVMNT_TYPE_H
